FROM node:22-slim

# Set working directory
WORKDIR /website

# Copy package files
COPY package*.json ./

RUN npm install --production
# Install dependencies
# RUN npm ci --production
# RUN apt-get update && apt-get install -y sqlite3 && rm -rf /var/lib/apt/lists/*


# Copy application code
COPY . .

# Expose the port your app runs on
EXPOSE 3000

# Start the application
CMD ["node", "server/routes/app.js"]